# Generated by Django 4.0 on 2022-01-04 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory_tracker.menuitemcategory', verbose_name='Item Category'),
            preserve_default=False,
        ),
    ]
